### ISSUE TITLE
File Source / Score Upload Form

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/elvis-database#102]
If multiple files of the same score are being uploaded it gets tedious to type “Transcribed by Uploader” maybe have the field autofilled when using “Transcribed by Uploader”, of from the previous File Source field if it’s the same piece.

**Comment by lexpar** [comment]
I don't know it auto filling would be a good solution, mainly because it could create situations where you don't want the field autofilled, and now you have to delete the auto-filled things and write in your new thing - which is probably equally annoying.

Copying and pasting works - or, the site does allow multiple file selection and uploading of zip files if they are all being attached to the same source.

**Comment by musicus** [comment]
Your reasoning is sound on this issue.
