### ISSUE TITLE
proposed edit to Movement Titles tooltip

### ISSUE THREAD

**Issue by NinaPenner** [ELVIS-Project/elvis-database#104]
Since users may enter the movements one at a time, possibly not starting with Movement 1, I think users should be encouraged to number the movements. But I think we should also encourage users to make spaces for all the movements in the piece, even if they don't have files for them at the time of uploading. (Emily and I have discussed how this wouldn't have occurred to us.) In which case, I propose the following edit: "If possible, enter movement numbers and titles for all movements, even those for which you may not have files." What do you think @emilyhopkins? This is getting a bit anal but do we want to standardize the movement numbering system as either Roman or Arabic numbers? I think it would look nicer if there was some sort of standardization. I've been employing the convention: "I: Allegro" or just "I" if there isn't a tempo designation or title.

**Comment by emilyhopkins** [comment]
Perhaps the ability to override the automatically assigned movement numbers is a better solution?

I've just been entering movement designations by themselves -- "Allegro" -- since the numbering is automatically done in the database. Since most entries benefit from the automatic numbering, having an override option for exceptional cases makes more sense to me than trying to enforce arabic/roman numerals, etc, to make it possible to enter movements out of order.

**Comment by NinaPenner** [comment]
Sure, that sounds fine, @emilyhopkins . In that case, I think it becomes even more important for users to make placeholders for all movements. So, how about we retain all the existing text and simply add at the end "Please enter the titles for all movements, even those for which you will not be uploading files."?

**Comment by emilyhopkins** [comment]
I like that solution, but this wording is better:
"Please enter the titles for all movements, even if you will not be uploading files for all of them."

**Comment by NinaPenner** [comment]
Sure.

**Comment by lexpar** [comment]
So - is the consensus that I should just change the text to encourage users to add movement titles even if they don't have files? Because that's about the best I can do.

Maybe I could add the ability to custom-order the movements. That way if the original piece had movements 1 and 3-9, you could add movement 2 and simply renumber 3-9 as 4-10.

**Comment by emilyhopkins** [comment]
I think the text-change solution is fine; people should be able to enter movement titles even if they don't have the files.

Custom-movement ordering would probably be good, but I'm confused by your example -- ideally users would never have to enter movements with the wrong number, so movment 3 would always be 3, no matter which other files were there...?

**Comment by lexpar** [comment]
What I meant is - say someone uploaded a piece a while ago, and its movements looks like this:

 - The first Movement
 - The third Movement

You could go into the update page, and it would look like this:

 - [1] The first Movement
 - [2] The third Movement

Then you could add and renumber things. This would be the only way for me to implement this kind of behaviour without rewriting a *lot* of stuff.

 - [1] The first Movement
 - [3] The third Movement
 - [2] The second Movement

**Comment by emilyhopkins** [comment]
Yes, that is a good idea. Things would get pretty ugly otherwise. Thanks for explaining so clearly.

**Comment by lexpar** [comment]
Text changed in a896bfe6d57c8721821f4dcbd5d74671117e6348 and feature added in 16823eb3d34a5342694c6bf9ff7b47c217a7989f
