### ISSUE TITLE
No sources for movement files?

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#111]
This is fairly minor, and seems to only be relevant to editing older entries. When revising older entries we may run in to trouble since the Piece files used to be the only ones that required sources (instead of Piece and Movement). (At least I think that's what happened.)

![screen shot 2015-08-19 at 4 49 57 pm](https://cloud.githubusercontent.com/assets/13374693/9368657/88832ec4-4692-11e5-94b0-da89407fd4e5.png)

As I understand it, the above shouldn't be possible -- that's the Update form, with no sources listed for any files. It's because I deleted the incorrect Piece files, keeping the Movement files, without adding any other Source information (it didn't occur to me at the time).

Obviously this won't be a problem with new uploads but could affect editing of older entries. Is there a way to force the updating to include source for all files?

**Comment by lexpar** [comment]
I actually wasn't checking for sources being required on the upload or update templates before, because you could have a non-static number of inputs, it was difficult to check. I've changed this now.

Here's the rules I've implemented for the dynamic form tables.

When Uploading:
A movement row without a title entered is ignored.
A file row without a file selected is ignored.
A file row that has a file selected *must* also have a source specified.

When Updating:
An existing movement row without a title throws a form validation error (this occurs when a user deletes the title of a movement instead of clicking the x button to delete it).
A new movement row without a title is ignored.
An existing file row *does not* require a source. This is because the only pieces that will have this case were created in the past - so the updater may have no way of knowing the file source.
A new file row without a file selected is ignored.
A new file row that has a file selected *must* also have a source specified.

If you have the chance to test these cases, it would be helpful! I could have missed something.

Fixed in 290d6b5d8e99fd053aa4f8b53b83e9281060dc10

**Comment by emilyhopkins** [comment]
Tested: "An existing movement row without a title throws a form validation error (this occurs when a user deletes the title of a movement instead of clicking the x button to delete it)."

I tried deleting the title of a movement, and instead of throwing an error it reassigned the file to the piece... see below, there is a blank next to the first movement and now two files are attached to piece...
![screen shot 2015-08-20 at 2 41 39 pm](https://cloud.githubusercontent.com/assets/13374693/9392289/dddf7d3e-4749-11e5-90eb-4ac9ca6c9bd0.png)

**Comment by emilyhopkins** [comment]
All the other cases you mentioned seem to work too. Thanks!
