### ISSUE TITLE
Home Page updates

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#112]
I'm creating this since it was discussed at the meeting -- @ahankinson and @NinaPenner brought up the need to update home page (http://database.elvisproject.ca/) so that it's clearer what the site does, how to get an account, etc. (Perhaps they have more to add?)

**Comment by lexpar** [comment]
Added a search bar and a nice logo to front page - removed big ugly icons and link text. Let me know what ya think.

**Comment by emilyhopkins** [comment]
I like it, but I think the comments were as much about function/content as aesthetics -- a couple things, based on my own looking at it as well as things from the meeting: 
1. needs to be more obvious that you need an account for most things, and how to get that account

2. I also don't love that I can't click on the Search, Download, Create, and that I have to look around to the little buttons at the top instead. Both or just the big ones might be better.

3. I still think "Create" should be "Upload" or "Add" or "Contribute" instead as we discussed before, and that the terminology should be consistent throughout the site (I'm guessing we just hadn't changed the front page? As it is in order to "Create" you have to know to click the "Upload" button, which is not ideal!

4. I do like the big search bar! Very nice.

**Comment by lexpar** [comment]
1.I don't want to put a big "get an account before doing anything else" button on the front page, because searching, browsing, and accessing individual files *should* be allowed to people who aren't logged in. Some changes I can make
- Put a special warning on the search page (the page an anonymous person is now most likely to go to) telling users they should get an account and log in.
- Have the download/upload pages redirect to the log-in page when accessed by an anonymous user.

2. I'm not going to get rid of the little buttons in the header... They are the only consistent way to get around the site. I will again make the front page headers into links.

3.Sure. I haven't 100% made up my mind about if I prefer "upload" to "create" (since there's quite a bit of work involved beyond just plunking a file onto the server), but it's better to just stick to upload for consistencies sake.

4. Thanks!

**Comment by emilyhopkins** [comment]
"creating a piece" still sounds like composing to me. I think Upload is okay; Contribute might be ideal but either way, consistency is good!

Do you think the ELVIS acronym should be spelled out somewhere? It seems a little odd to leave it totally unexplained but it is a bit cumbersome as well...

**Comment by lexpar** [comment]
Maybe... I've checked now and it doesn't look like the http://elvisproject.ca/ website ever explains the acronym.

**Comment by emilyhopkins** [comment]
Even NASA explains it in the fine print! Maybe we should ask at the meeting tomorrow.

**Comment by AFFogarty** [comment]
Has everything discussed here been resolved?  Can we close this issue?

**Comment by lexpar** [comment]
I say it's done. We have a search bar, the upload/update stuff is being put under a 'create' button, and the ELVIS acronym is explained on the about page.
