### ISSUE TITLE
Create Account for New User not working in Safari

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#119]
Ian Lorenz (new grad student)  was trying to make an account and came across this problem using Safari. He says after filling out the info and doing the I'm-not-a-robot bit it shows this error, and has done so several times:

![screen shot 2015-09-08 at 10 40 57 am](https://cloud.githubusercontent.com/assets/13374693/9737972/4ae97746-5617-11e5-89a6-cab6d96e6f94.png)

Any idea what might be going on? Thanks!

**Comment by lexpar** [comment]
Hey Emily,

Thanks for sending this my way. Was able to find and fix the bug pretty
quickly. Turns out those new captchas were causing some problems after the
Python 3 transition. Since I implemented both those things in the last
couple days of work, I didn't notice the issue.

Please let me know if everything's working now!

-Alex

**Comment by emilyhopkins** [comment]
He says it's working now, thanks Alex!
