### ISSUE TITLE
`+` Indicators

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/elvis-database#148]
When not being logged in, the green `+` indicators do not show up on the search results. I think they should show up on the search results, and once clicked, prompt the user to log in, or create a user account.

**Comment by musicus** [comment]
So I'm at a conference showing the database to users, and it's extremely unfortunate that this small issue has not been resolved.

**Comment by lexpar** [comment]
I got an email pertaining to a comment you must have added and then deleted, or isn't showing up here for some reason. If you thought this issue was urgent and time critical, you should have let me know. I agree that this is a good idea. I spent about 6 hours on Thursday working on Misirlou, and I surely could have implemented this in that time had you told me that it was pressing.

**Comment by musicus** [comment]
No worries. I was being too sensitive, earlier, I didn't have my coffee.
