### ISSUE TITLE
Movement files don't include piece name in title

### ISSUE THREAD

**Issue by alexandermorgan** [ELVIS-Project/elvis-database#158]
If you download all of the movements of a piece, the files that get downloaded just show the movement in their title. This has the huge side effect that if you're downloading more than one multi-movement piece by the same composer where the movements would have the same names, not all of the movements get saved because they have the same titles and so they seem to be writing over one another.
For example, if you want to download all of the movements of two masses by Du Fay, those movements will have mostly the same names (Kyrie, Credo, Gloria, etc.) so they will write over one another at some point in the process.
This is a big problem but the solution seems pretty easy: include the piece name in a movement file's name. In addition, there should probably be some way of handling naming collisions like this because the movement name, piece name, and composer name could be the same but the music could still be totally different (like two mass Kyries written by an anonymous composer).

**Comment by lexpar** [comment]
Good point - I didn't so this because there was a possibility of file names getting incredibly long.

I've been wanting to implement directory hierarchies in the downloaded zip for a long time (#74)...
Like, instead of just getting all the files in one folder, getting a number of folders in the zip file with the composers name, and then in those the pieces names, etc... This would solve this organization issue, and I think is preferable to 300 char long file names.

**Comment by AFFogarty** [comment]
@lexpar is this solved?

**Comment by lexpar** [comment]
YUP.
