### ISSUE TITLE
Zip File Name

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/elvis-database#184]
The name of the zip file is a bit unintuitive. It also contains characters other than alphanumeric, "-", "_", and ".", which we decided to avoid for file names. When a zip download is created from a collection it should probably have at least the name of the collection in it, or perhaps the user should be able to name the zip file to be downloaded.

**Comment by lexpar** [comment]
Every modern browser asks you what you want to name and where you want to save a downloaded file. Why would we program that in to the website, when it exists in *every* browser?

Are you referring to opening and closing brackets being an issue in filenames? Those are in the ascii range, and every Windows/POSIX system can deal with them.

The default zip-file names are designed only to sort into the order you downloaded them in, and avoid duplicate naming. It is a default that offers two nice things. The default can be over-ridden easily, by anyone. I don't see an issue here.

**Comment by musicus** [comment]
So why, when downloading a file collection via a .zip from the database, are you not being prompted by the browser what to name the file, but instead get an automatically named file then? 

Yes, every Windows/POSIX system can deal with it, but we previously had established with the automatic file naming scheme of scores that are being uploaded the we should only use alphanumeric, `-`, `_`, and `.` characters (refer back to the [Stanford's best practices for file naming](https://library.stanford.edu/research/data-management-services/data-best-practices/best-practices-file-naming)). We should always be **consistent** in how we automatically name files, thus it is an issue that needs to be solved.

**Comment by lexpar** [comment]
I agree that I should remove the `(` and `)` in zip file names. They are ugly. I added them to demarcate day from time, but I agree that they don't look very good. That Stanford article is pretty cool. 

I disagree about letting users name a zip file before they request it. I disagree because it's a feature that, on the best day, saves a few seconds for a user. On most browsers, you get the option to choose where to download a file and what to name it by default. Maybe safari is an exception. Even if it is, it takes a second to rename a file on your computer. Almost no site on the internet lets you name a file *before* you download it. It's not a reasonable expectation because it's just so easy to just rename the file when its on your computer.

**Comment by musicus** [comment]
That's fine it was an _or_, and I am aware that it is a Safari only issue (depending on how you set your preferences, I always go from the premise of "I don't know how to use a computer" when testing for usability). The file naming issue, as the title of the issue suggests, regarding using only the specified characters, is what's most important here.

**Comment by AFFogarty** [comment]
Yeah, letting users rename the file before download makes no sense to me.

**Comment by AFFogarty** [comment]
Ok, I've modified the file names a bit.  They now look like this:

```
ElvisDownload-20160210-211039.zip
```

**Comment by musicus** [comment]
:+1: Belle job! Closing issue.
