### ISSUE TITLE
Zip feature on dev site

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/elvis-database#185]
The zip/download feature is currently not working on the _dev_ site.

**Comment by lexpar** [comment]
This isn't a bug, nor is it high priority. We've done nothing to set up media services on the dev site yet. We're not doing any development in that area right now, so it's not been a priority (setting up the new framework on the server, with updated Django, Solr, DB schema and caching, moving from apache to nginx: those were the priorities).

It might even be a bad idea to ever set up the media services for the dev site. We don't want people accidentally uploading or modifying files on the dev site (having no effect on the *actual* files), and we don't want to hook up the dev site to the normal file store, and we don't want to have 4 copies of all the files on the EDB.

Plus, in general, the media service is a fairly stable part of the site. Once we refactor some things so that nginx is serving files independently of django, there will be very little that will be actually changing on this end of things.

**Comment by musicus** [comment]
We absolutely need to have media services on the _dev_ site. How else will we know what we have developed is buggy, if we can't work with media services? Case in point is this particular bug. I can access files, compile them into a collection, but I cannot zip and download them. Certainly that is something that needs to be reported when it does not work on the _dev_ site. We do want to have 3 copies (not 4) of all files, and we even asked Compute Canada to give us enough space for Julie's allocation so we can accomplish just that. 

_dev_ sites should always have the exact same functionality as production sites. If we don't properly find and squash bugs with an appropriate simulation on the dev site, we could possibly push those to production. We want to avoid moving bugs to production: that is the very reason we have a _dev_ and _staging_ sites.

Clearly this is not a big deal, since all you guys have to do is refactor. However, not being able to download files is one of the major functionalities of the database, and that is a big deal, thus a high priority bug, even if it is on the _dev_ site. You do not have to immediately fix this issue, since it is not a _Blocker_, so no sweat, but please do fix it.

**Comment by lexpar** [comment]
I think I was wrong to suggest that there might be *no* media service features on the dev site. I have some concerns about whether it makes sense to triplicate our files (I don't think it does), and I don't like the idea of someone who uses both the dev and prod sites frequently confusing the two and adding/getting media that's out of date or in the wrong place. I think it makes the most sense to have a small set of test files shared between the dev and stage servers. I also think we need to put a sign on the sites that warn people that they are not vising the right site to download and upload files.

More than anything, I was trying to emphasize that this isn't a bug (and certainly not high priority) because we *haven't set that part of the site up yet*. We have to be finished setting up the site for bug reports to be meaningful. I got a little frustrated that we had a high priority bug about a section of the site that we haven't bothered to implement yet, since its low on our priorities.

Sorry if I'm sounding combative today, I'm catching a cold and in a crud mood.

**Comment by musicus** [comment]
The only people using the _dev_ and _staging_ site are going to be people in the lab, nobody else (including the musicologists working with us generally on the ELVIS project). So your concern is valid if everybody was on it, but that is not the case. The data that is the most important is the one on the production site, and from time to time, we'll update the _dev_ and _stage_ data from the production site, never the other way around. All three sites need to have all the data, I do test very specific tasks, and only if we have all the data can we be re-assured that everything works correctly.

This issue is only for the future, I don't consider it a _bug_ per se (but if it's not working as intended it is a bug). And more importantly by having a _dev_ site, bugs that do occur are never as severe even if they are high priority, since we'll have a pristine perfectly working site on production. :). It's merely on the todo list and I downgraded it to _low_, as you may have noticed. And please, I do know that you are not quite done yet, and I do appreciate all the work you guys put into this project.

I value your opinion combative or not.

**Comment by ahankinson** [comment]
Bugs can certainly be shaken out on _dev_ sites, but bug finding and fixing is really the job of unit tests. Django, and Django REST Framework come with some nice tools for building unit tests, with the nice thing being that you can simulate a real client interaction over the API.

Having so many servers seems like a lot of administrative overhead -- certainly `dev` and `production`, but isn't`staging` overkill? The devs will spend most of their time debugging deployments than actually fixing code...

**Comment by musicus** [comment]
Unit testing is great for bugs in the actual code, and we should always make sure all tests are written in parallel with development. However, unit-testing, doc-string testing, etc., are not particularly useful identifying usability bugs and issues, especially when they are written by the developer. One example that came up whe

**Comment by musicus** [comment]
Unit testing is great for bugs in the actual code, and we should always make sure all tests are written in parallel with development. That said, unit-testing, doc-string testing, etc., are not particularly useful identifying usability bugs and issues, especially when they are written by a developer.

True, having more servers will create a little bit of administrative overhead, but some of that overhead is going to be automated. The `dev` > `staging` > `production` workflow is a commonly used paradigm, and I think we will benefit from using it in the big picture, once it is in place and running.

**Comment by ahankinson** [comment]
I would rather we keep the dev/production setups we are currently using. There are only a few people in the project that we can ask to help us test, and asking them to keep the differences between 'dev' and 'staging' systems straight for the purposes of usability testing would just make it all the more confusing. 

We are not a huge organization, and we don't have dedicated devops to deploy and maintain systems, so we rely on our developers to do this, and they have better things to do. We should keep it simple.

**Comment by musicus** [comment]
The `staging` stage is not for usability testing, and it is _only_ for our developers. The `dev` stage is for usability testing for people in the lab, testing new features, unit testing, etc. Currently we do not have a formalized `dev` > `production` workflow model in place. In addition, we are also an educational organization, and from that perspective we should have the full workflow in place, since that is something our people will encounter elsewhere.

**Comment by ahankinson** [comment]
But why? Presumably our devs have the site set up on their own machines too, so that makes four different installations to maintain.

**Comment by musicus** [comment]
The OS X based server environments on the developers machines are quite a bit different than the server environments that we are using on production. To have a `dev` environment on exactly the same system as `production` will greatly aide our deployments.

**Comment by ahankinson** [comment]
That's fine. `dev` and `production` are good. What's with `staging`?

**Comment by musicus** [comment]
Ok. We can simplify it by only using `dev` > `production`, as long as `dev` is on exactly the same system (with the same data) as the `production` server.

**Comment by AFFogarty** [comment]
Late to the party, but here are my 2 cents:

> We absolutely need to have media services on the dev site. How else will we know what we have developed is buggy, if we can't work with media services? Case in point is this particular bug. I can access files, compile them into a collection, but I cannot zip and download them. Certainly that is something that needs to be reported when it does not work on the dev site.

I agree with this.

> I don't like the idea of someone who uses both the dev and prod sites frequently confusing the two and adding/getting media that's out of date or in the wrong place.

Non-developers should not have user accounts on the dev site.

> That's fine. `dev` and `production` are good. What's with `staging`?

The point of `staging` is to have an environment where we can prepare builds for `production`.  Developers are only ever working with `staging` to make sure that we've dotted the i's and crossed the t's before we push code to `production`.  That way, we can triage any deployment problems without bringing down the `production` site.  Meanwhile, the `dev` site might be many commits ahead of the  `staging` and `production` sites.

Here is a pretty good diagram that demonstrates this kind of workflow:

![](https://ffwagency.com/sites/default/files/inline-images/Building-Quality-3.png)

**Comment by ahankinson** [comment]
I understand the use of staging in other environments. I just don't think it's suitable in *our* environment.

However, I suspect in this discussion it's a confusion of naming. To me, "dev" = "local development instance" and "stage" = "dev". Since our teams work side by side and can actually talk to each other, I don't see any need for creating another VM just for "dev" purposes.

**Comment by lexpar** [comment]
I think @ahankinson is right that we've been using conflict terminology to debate something we all agree on. The only misunderstanding is whether both 'dev' and 'stage' should be deployed on the server and accessible over the web. 

It doesn't make sense to me to have 3 websites hosted at all time (dev, stage, prod). It makes much more sense to call the new site we've put up (dev.database.elvisproject.ca) our 'stage' and treat our local environments as 'dev'. I don't know what we'd gain from having 2 live 'test' sites.

**Comment by musicus** [comment]
Let's stop the deflection and re-focus on the actual issue here: Is the zip/download feature working on the dev site?

**Comment by AFFogarty** [comment]
I'm going to create a new thread for all future server environment discussion.

**Comment by AFFogarty** [comment]
Fixed in 37fbe466c391296a207615d61db142bea32fd8aa.

**Comment by musicus** [comment]
:clap: :neckbeard: :musical_note:
