### ISSUE TITLE
Committing Username

### ISSUE THREAD

**Issue by AFFogarty** [ELVIS-Project/elvis-database#192]
Is it safe to commit a configuration file to the repo that contains my SSH username for the server?

**Comment by ahankinson** [comment]
I wouldn't.

**Comment by lexpar** [comment]
You username in no way exposes your public key. You public key is stored in /home/afogarty/.ssh on the server, but someone would already have to be on the server in order to exploit that connection.

**Comment by AFFogarty** [comment]
@lexpar In a discussion of whether or not to reveal my username, it is best not to reveal my username.

**Comment by lexpar** [comment]
¯\_(ツ)_/¯

Sometimes the default-to-paranoia with web-security stuff feels weird to me. I guess it's for the best though.

**Comment by AFFogarty** [comment]
Ok, I won't commit it.

**Comment by ahankinson** [comment]
A few years ago a MT professor (let's call him "Paul" for the sake of anonymity) would periodically get locked out of his music tech server account. The server had a mechanism where more than X number of failed attempts would disable the account, which was being triggered somehow. Turns out that someone was doing a username dictionary attack against the server, and `paul` was one of the usernames they were trying to crack. Drove him batty for a bit until we figured it out.

It's not paranoia if they're out to get you. Security through obscurity isn't the only mechanism you should use, but it certainly goes a long way in helping.

**Comment by lexpar** [comment]
Point taken.

**Comment by AFFogarty** [comment]
:+1: :lock:
