### ISSUE TITLE
Merging Dev Into Production

### ISSUE THREAD

**Issue by AFFogarty** [ELVIS-Project/elvis-database#196]
Which issues are currently preventing us from merging the `dev` branch into the `master` branch and deploying the site to production?

The build currently deployed into production is quite ancient.

**Comment by lexpar** [comment]
#195 is obviously something you'd like to avoid on the production server. As far as I can tell, something about how the 'all' keyword gets passed to the views is messing up. It's probably a 1-line fix if you just wanna nip it and move forward. I suggested waiting because I'd like to further refactor cart-related stuff, and this sort of thing would likely change. 

Other than that, I can't think of any show-stopping issues...

**Comment by AFFogarty** [comment]
Ok.  I've created a new Milestone to track merging `dev` into `master`.  Any issues blocking us from deploying should be added to that milestone.

**Comment by musicus** [comment]
Great...I had the same thing in mind earlier this week. Either way here is a deadline: **March 15, 2016 - 17:00**.

**Comment by AFFogarty** [comment]
Cool.  I will go ahead and close this issue.  From now on, we will just add issues to the milestone.
