### ISSUE TITLE
Fix scrambled files that don't match what is shown in the database

### ISSUE THREAD

**Issue by vee-L** [ELVIS-Project/elvis-database#221]
Database files (likely most of them) got scrambled around, we should re-label/re-assign them to where they actually belong (through a possible backup/old db, or by using the xml info inside the files).

**Comment by lexpar** [comment]
How do we know what is and isnt scrambled? Where does the idea that most of them are scrambled come from? It doesn't make much sense that some would be shifted and not others if it was a site-wide problem.

**Comment by vee-L** [comment]
I'm just repeating what I heard at the elvis meeting today, someone tried to use the files in the db and for a composer (the first one in the list), the files he got didn't match with the name that was displayed in the db. We assumed if they were all messed up for one composer, it was likely to happen elsewhere (maybe someone who was at the meeting can clarify if I misunderstood what was said). @musicus @fujinaga

**Comment by lexpar** [comment]
Yeah I got an email from Ian today about this. It doesn't make a whole lot of sense... I wonder if this is a recent issue, or something that's been around for a long time and gone unnoticed.

**Comment by vee-L** [comment]
It seems like it could be due to a recent migration (I don't know when that happened) but I'm not sure.

**Comment by lexpar** [comment]
Possibly related - you can't download any files right now. This is so weird... I downloaded a file from the site this morning!

**Comment by vee-L** [comment]
I think you can't download anything right now if you're not on a mcgill computer because of #222

**Comment by lexpar** [comment]
Really? I wonder when that got put into place. I only heard about this being referenced at the SIMSSA talks last week.

**Comment by lexpar** [comment]
I would expect this issue to be general and relatively widespread if at some point data migration cause file names to jump around (although, I can't think of any instance that should have cause this to happen!)

Bach's BWV 588 and 589 appear to point to the correct midi files. Is it possible that the Agricola Alexander (this is the composer Ian mentioned) files were not properly uploaded in the first place? Please let me know if you find more examples of this.

**Comment by lexpar** [comment]
A random sampling of 3 of Chopin's pieces [Ballade No. 3 in A-flat Major, Op. 47](http://database.elvisproject.ca/piece/1547/), [Fantasy, Op. 49](http://database.elvisproject.ca/piece/1529/), [Nocturne No. 10 in A-flat Major, Op. 32 No. 2](http://database.elvisproject.ca/piece/1441/) all appear to be correct as well. 

I felts a little panicky once I saw this issue... But it looks like the files I'm sampling are all correct. It looks less and less like a system wide issue.

**Comment by musicus** [comment]
@lexpar it is possible that this is an issue only with the Agricola, but we also had a report at the lab meeting where it was the case with some Joaquin pieces...is there a back-up so we can cross-reference?

**Comment by lexpar** [comment]
The oldest backup I have is from shortly before me and Andrew redeployed the site... I can't give you an exact date on that: it's not really a backup, just the previous version of the site (the files still exist). Otherwise, we only have 3 weeks of rolling backups at a time. 

I checked using one of Ian's examples of a 'swapped' files (http://database.elvisproject.ca/piece/200/), and the md5sum of the file is the same of the oldest copy and our current production deployment. That is, the same file has been there since January when we redeployed things.

So either:

1. The 'swapping' happened at some indeterminate point more than 4-5 months ago.
2. These files have always been mixed around.

I find it highly unlikely that any swapping every occurred. Our example file, In Minen zin, lives in its own directory with no files next to it. None of the renaming of files we've ever done has ever preceded by composer/directory either, it's always been simply through iteration over the `Attachment` models in the database. Nothing I did would have transferred a file from one piece to another, or 'swapped' them.

**Comment by ahankinson** [comment]
I'm the culprit for restricting downloads. There is a rule in place on the nginx server that will restrict downloads to only McGill IPs. This is because we got a complaint about redistributing files and we're trying to sort it out. Sorry I did not communicate this clearer.

**Comment by lexpar** [comment]
No need for apology. I haven't gone to any elvis meetings in a while, so it makes sense that I would be out of the loop.

**Comment by vee-L** [comment]
So....is there anything I can/should do about this? I don't know which files are scrambled or if it<s just a mistake and not a database screw up, and I don't think I have access to the backups.

**Comment by lexpar** [comment]
Like I mentioned earlier, we don't have any backups which appear to differ in respect to files being shuffled around. I have to agree with you @vee-L: unless someone can find some sort of pattern to support the existence of a systematic error, there's nothing you or I can do. So far, all I've heard are that 2 pieces by Agricola Alexander are mislabeled, and there's the Joaquin pieces @musicus mentioned (we don't know which in particular though). 

I know this issue was brought up by Ian. If he or anyone else finds some sort of pattern here, then we can actually do something.

**Comment by musicus** [comment]
@lexpar contact Malcolm about the _Josquin_ pieces.

**Comment by lexpar** [comment]
I'm not sure I know who Malcom is... In any case, I don't want to get too involved in this beyond offering support for @vee-L, so perhaps you could pass the contact information on to her?

**Comment by musicus** [comment]
@vee-L can get Malcolm's info at the ELVIS meeting.

**Comment by imlorenz** [comment]
Alex, I can give you access to the google doc that I have created documenting the ELVIS Metadata, but there are quite a few files that are incorrect.  Here is a list of Agricola files that are incorrect thus far: J'en ay dueil (chanson), In minen zin (chanson), Missa Malheur me bat, Missa In minen zin, Missa Je ne demande, Missa Le Serviteur (2 of the five movements are incorrect), and Si dedero.  But this problem persists beyond Agricola because the Wegman file for Missa Auleni (composed by Aulen) is not correct either.  It is possible that there is a method to how movements got mixed up, but I haven't figured it out as of yet.

**Comment by ahankinson** [comment]
Just to clarify: @vee-L will be fixing this; @lexpar is simply acting as an advisor.

**Comment by musicus** [comment]
Yes. That is what we discussed at the last ELVIS meeting.

**Comment by lexpar** [comment]
I'm glad to hear you are cataloging the issues you find Ian. Hopefully you can figure something out... Are the 2/5 movements that are incorrect on Missa Le Serviteur swapped with each other, or pointing to completely unrelated files? Actually, I'm not sure how either result would support a pattern here... Why would only 2/5 movements be swapped, or pointing to different files?

**Comment by lexpar** [comment]
This has been resolved. There is documentation in the repo describing what was done.
