### ISSUE TITLE
Can't uncheck facets with " 's " in them

### ISSUE THREAD

**Issue by lmok** [ELVIS-Project/elvis-database#30]
Encoding issue: JS can't detect "%27s" as "'s", which probably comes from my encoding antics in solrsearch.py. Though, the facets do work with accented characters, whitespaces, and so on.

**Comment by lexpar** [comment]
I believe the issue is that the facet itself is getting the name "Catherine's Corpus", and the line
`$("input[data-facet-name='" + param + "'][data-facet-value='" + val + "']").attr('checked', true)` fails because `[data-facet-value=' Catherine's Corpus ']` now has messed up single quotes.

Probably shouldn't use this field to index things. Since the div itself looks like this:

`<input type="checkbox" class="facet-link" data-facet-name="parent_collection_names" data-facet-value="Catherine's Corpus" id="facet-link-Catherine's Corpus-parent_collection_names">`

We could change how id's are being named (convert to URI first or something) and then use id's to index.

**Comment by ahankinson** [comment]
The facet names can be URL encoded to display correctly, so "Catherine%27s%20Corpus".

**Comment by lexpar** [comment]
Yup, just did it!

The problem was that, in a few places encoding wasn't being down at all, and in the places it was `URIencode()` was being used - which actually ignores `'` chars.

I replaced those with `escape()` and things work now.

But it would be nice if selecting a facet would just get JQuery to send the params to /search/ and then plop the JSON in the results div - rather than reloading the page every time a facet is selected. New issue.
