### ISSUE TITLE
Attach To dropdown menu

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#88]
This is a small thing:

When I click the dropdown, I choose a movement and click it, the checkmark shows up, and the menu stays open. Is there a good reason not to automatically close the dropdown options once one is selected? 

(Overall I like the new upload system A LOT! I put up a bunch of wind quintets today and found it much nicer to use. Thanks for all your work!)

**Comment by lexpar** [comment]
I agree that was no good... I actually fixed it yesterday but forgot to update the live site. I originally had the dropdowns in `you can select multiple things to a maximum of 1 thing(s)` mode because for some reason it looked better than `you can only select one thing mode`... But it also kept the dropdowns open after click. Anyway, its better now. Fixed in 03faaeadd524a19c7139618618fa87708f676852
